Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -51,6 +51,20 @@ jobs:
           rm -rf test
           sed -i 's/flutter.minSdkVersion/23/' android/app/build.gradle*
 
+      - name: Add Firebase config
+        working-directory: ${{ env.PROJECT_DIR }}
+        run: |
+          if [ ! -f android/app/google-services.json ]; then
+            JSON=$(find "$GITHUB_WORKSPACE" -name google-services.json -not -path "*/.git/*" | head -n 1)
+            if [ -z "$JSON" ]; then
+              echo "Error: google-services.json not found!"
+              exit 1
+            fi
+            cp "$JSON" android/app/google-services.json
+          fi
+          sed -i '/id("com.android.application") version/a\    id("com.google.gms.google-services") version "4.4.2" apply false' android/settings.gradle.kts
+          sed -i '/id("com.android.application")$/a\    id("com.google.gms.google-services")' android/app/build.gradle.kts
+
       - name: Get packages
         working-directory: ${{ env.PROJECT_DIR }}
         run: flutter pub get
