Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,6 +65,16 @@ jobs:
           sed -i '/id("com.android.application") version/a\    id("com.google.gms.google-services") version "4.4.2" apply false' android/settings.gradle.kts
           sed -i '/id("com.android.application")$/a\    id("com.google.gms.google-services")' android/app/build.gradle.kts
 
+      - name: Use fixed debug keystore
+        run: |
+          mkdir -p ~/.android
+          KS=$(find "$GITHUB_WORKSPACE" -name debug.keystore | head -n 1)
+          if [ -z "$KS" ]; then
+            echo "Error: debug.keystore not found!"
+            exit 1
+          fi
+          cp "$KS" ~/.android/debug.keystore
+
       - name: Get packages
         working-directory: ${{ env.PROJECT_DIR }}
         run: flutter pub get
